Part 1: NumPy
Question 1 – Create and Analyze an Array
Create a NumPy array containing the ages of 10 employees.
Tasks:
Print the array.
Print the highest age.
Print the lowest age.
Print the average age.
Print all ages greater than 30

In [2]:
import numpy as np
data=np.array([10,30,24,34,56,67,45,34,23,45])
print(max(data))
print(data)
print(min(data))
print(sum(data)//len(data))
print(data>30)

67
[10 30 24 34 56 67 45 34 23 45]
10
36
[False False False  True  True  True  True  True False  True]


Question 2 – Indexing and Slicing
Create an array containing numbers from 1 to 20.
Tasks:
Print the first five elements.
Print the last five elements.
Print elements from index 5 to 10.
Print every second element.
Reverse the array.

In [5]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(data[:6])
print(data[-6:])
print(data[5:11])
print(data[0:len(data)+1:2])
print(data[::-1])

[1 2 3 4 5 6]
[15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[ 1  3  5  7  9 11 13 15 17 19]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


Question 3 – 2D Arrays
Create a 3×4 matrix.
Tasks:
Print the matrix.
Print the second row.
Print the third column.
Print the element at row 2, column 3.
Print the last row.

In [17]:
import numpy as np
data=np.array([[1,2,3,4],[5,6,7,8],[9,24,3,6]])
print(data.ndim)
print(data.shape)
print(data)
print(data[1])
print(data[:,2])
print(data[1][2])
print(data[-1])

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 24  3  6]]
[5 6 7 8]
[3 7 3]
7
[ 9 24  3  6]


Question 4 – Broadcasting
A teacher decides to add 5 marks to every student's marks.
Create:
80 90 70
60 75 85
90 95 88
Tasks:
Add the bonus using broadcasting.
Print the updated marks.
Print the average marks of each student

In [21]:
import numpy as np
data=np.array([[1,2,3],[5,6,7],[9,24,3]])
a=data+5
print(a)
d=np.mean(a,axis=1)
print(d)



[[ 6  7  8]
 [10 11 12]
 [14 29  8]]
[ 7. 11. 17.]


Question 5 – NumPy Calculations
Create an array containing employee salaries.
Tasks:
Increase every salary by 10%.
Find the average salary.
Find salaries above the average.
Count how many employees earn above the average.

In [29]:
import numpy as np
data=np.array([1000,2000,3000,4000,5000,6000])
b=data+data*10/100
print(b)
d=np.mean(b)
print(d)
print(b>d)
c=np.sum(b>d)
print(c)



[1100. 2200. 3300. 4400. 5500. 6600.]
3850.0
[False False False  True  True  True]
3


Part 2: Pandas
Question 6 – Create a DataFrame
Create an employee DataFrame with:
Name
Age
Department
Salary
Tasks:
Print the DataFrame.
Print the first three rows.
Print the last two rows.
Print the shape.
Print the column names.
Print the data types.

In [44]:
import pandas as pd
data = {
    "age": [23, 34, 56, 23],
    "department": ["it", "non-it", "teacher", "railway"],
    "salary": [1000, 2000, 4000, 6000]
}
df = pd.DataFrame(data)
print(df)
print(df.head(3))
print(df.tail(2))
print(df.shape)
print(df.columns)
print(df.dtypes)

   age department  salary
0   23         it    1000
1   34     non-it    2000
2   56    teacher    4000
3   23    railway    6000
   age department  salary
0   23         it    1000
1   34     non-it    2000
2   56    teacher    4000
   age department  salary
2   56    teacher    4000
3   23    railway    6000
(4, 3)
Index(['age', 'department', 'salary'], dtype='str')
age           int64
department      str
salary        int64
dtype: object


Question 7 – Filtering
Use the DataFrame from Question 6.
Tasks:
Salary > 50000
Department = IT
Age between 25 and 30
Display only Name and Salary
Employees from HR with salary greater than 45000

In [ ]:
import pandas as pd
data = {
    "name": ["Asha", "Rahul", "Priya", "Kiran", "Ravi"],
    "age": [23, 28, 30, 35, 27],
    "department": ["IT", "HR", "IT", "HR", "Finance"],
    "salary": [40000, 50000, 60000, 55000, 45000]
}
df = pd.DataFrame(data)
print(df)
print(df[df["salary"] > 50000])
print(df[df["department"] == "IT"])
print(df[(df["age"] >= 25) & (df["age"] <= 30)])
print(df[["name", "salary"]])
print(df[(df["department"] == "HR") & (df["salary"] > 45000)])


    name  age department  salary
0   Asha   23         IT   40000
1  Rahul   28         HR   50000
2  Priya   30         IT   60000
3  Kiran   35         HR   55000
4   Ravi   27    Finance   45000

Employees with Salary > 50000:
    name  age department  salary
2  Priya   30         IT   60000
3  Kiran   35         HR   55000
    name  age department  salary
0   Asha   23         IT   40000
2  Priya   30         IT   60000

Employees with Age between 25 and 30:
    name  age department  salary
1  Rahul   28         HR   50000
2  Priya   30         IT   60000
4   Ravi   27    Finance   45000

Name and Salary:
    name  salary
0   Asha   40000
1  Rahul   50000
2  Priya   60000
3  Kiran   55000
4   Ravi   45000
    name  age department  salary
1  Rahul   28         HR   50000
3  Kiran   35         HR   55000


Question 8 – Reading Data
Create a DataFrame and save it as:
CSV
Excel
JSON
Read all three files back into Pandas and print them.

In [47]:
import pandas as pd

# Step 1: Create the DataFrame
data = {
    "Name": ["Ravi", "Sita", "Arun", "John"],
    "Age": [25, 28, 30, 35],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 45000, 60000, 70000]
}

df = pd.DataFrame(data)
# Step 2: Save the DataFrame
df.to_csv("employees.csv", index=False)
df.to_excel("employees.xlsx",index=False)
df.to_json("employees.json", orient="records")

print("Files saved successfully.\n")
# Step 3: Read the CSV file
csv_data = pd.read_csv("employees.csv")
print("CSV File")
print(csv_data)

print()
# Step 4: Read the Excel file
excel_data = pd.read_excel("employees.xlsx")
print("Excel File")
print(excel_data)
print()
# Step 5: Read the JSON file
json_data = pd.read_json("employees.json")
print("JSON File")
print(json_data)

Files saved successfully.

CSV File
   Name  Age Department  Salary
0  Ravi   25         IT   50000
1  Sita   28         HR   45000
2  Arun   30    Finance   60000
3  John   35         IT   70000

Excel File
   Name  Age Department  Salary
0  Ravi   25         IT   50000
1  Sita   28         HR   45000
2  Arun   30    Finance   60000
3  John   35         IT   70000

JSON File
   Name  Age Department  Salary
0  Ravi   25         IT   50000
1  Sita   28         HR   45000
2  Arun   30    Finance   60000
3  John   35         IT   70000


Question 9 – GroupBy
Using the employee DataFrame,
Find:
Average salary
Total salary
Maximum salary
Minimum salary
Employee count

In [49]:
import pandas as pd

data = {
    "Name": ["Ravi", "Sita", "Arun", "John", "Priya", "Kiran"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 45000, 60000, 70000, 48000, 65000]
}
df = pd.DataFrame(data)
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].sum())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Salary"].min())
print(df.groupby("Department")["Name"].count())

Department
Finance    70000.000000
HR         46500.000000
IT         58333.333333
Name: Salary, dtype: float64
Department
Finance     70000
HR          93000
IT         175000
Name: Salary, dtype: int64
Department
Finance    70000
HR         48000
IT         65000
Name: Salary, dtype: int64
Department
Finance    70000
HR         45000
IT         50000
Name: Salary, dtype: int64
Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64


Question 10 – Missing Values
Tasks
Count missing values.
Fill missing Age.
Fill missing Salary.
Remove rows containing missing values.
Print the final DataFrame.

In [48]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ravi", "Sita", "Arun", "John"],
    "Age": [25, np.nan, 30, 28],
    "Salary": [50000, 40000, np.nan, 45000]
}

df = pd.DataFrame(data)

print(df)

print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

print(df)

   Name   Age   Salary
0  Ravi  25.0  50000.0
1  Sita   NaN  40000.0
2  Arun  30.0      NaN
3  John  28.0  45000.0
Name      0
Age       1
Salary    1
dtype: int64
   Name        Age   Salary
0  Ravi  25.000000  50000.0
1  Sita  27.666667  40000.0
2  Arun  30.000000  45000.0
3  John  28.000000  45000.0


Part 3: Data Preprocessing 
Question 11 – Remove Duplicates
Create a DataFrame containing duplicate employee records.
Tasks
Identify duplicates.
Remove duplicates.
Print the cleaned DataFrame.

In [50]:
import pandas as pd
data = {
    "Name": ["Ravi", "Ravi", "Sita", "Arun"],
    "Age": [25, 25, 28, 30],
    "Department": ["IT", "IT", "HR", "Finance"]
}

df = pd.DataFrame(data)
df = df.drop_duplicates()
print(df)

   Name  Age Department
0  Ravi   25         IT
2  Sita   28         HR
3  Arun   30    Finance


Question 12 – Convert Data Types
Create a DataFrame where Age and Salary are stored as strings.
Convert them into integers

In [51]:
import pandas as pd

data = {
    "Name": ["Ravi", "Sita", "Arun"],
    "Age": ["25", "28", "30"],
    "Salary": ["50000", "45000", "60000"]
}

df = pd.DataFrame(data)

df["Age"] = df["Age"].astype(int)
df["Salary"] = df["Salary"].astype(int)

print(df)

print(df.dtypes)

   Name  Age  Salary
0  Ravi   25   50000
1  Sita   28   45000
2  Arun   30   60000
Name        str
Age       int64
Salary    int64
dtype: object


q:13 Complete Data Cleaning
Create a dataset containing:
Missing values
Duplicate rows
Incorrect data type

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ravi", "Ravi", "Sita", "Arun"],
    "Age": ["25", "25", np.nan, "30"],
    "Department": ["IT", "IT", "HR", "Finance"]
}

df = pd.DataFrame(data)
df = df.drop_duplicates()
df["Age"] = pd.to_numeric(df["Age"])
df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)

   Name   Age Department
0  Ravi  25.0         IT
2  Sita  27.5         HR
3  Arun  30.0    Finance


Part 4: Feature Engineering 
Question 14 – Student Report
Create:
Math
Science
English
Create:
Total
Average
Result

In [54]:
import pandas as pd

data = {
    "Student": ["Ravi", "Sita", "Arun"],
    "Math": [80, 70, 95],
    "Science": [90, 75, 88],
    "English": [85, 80, 92]
}

df = pd.DataFrame(data)

df["Total"] = df["Math"] + df["Science"] + df["English"]

df["Average"] = df["Total"] / 3

df["Result"] = df["Average"] >= 80

print(df)

  Student  Math  Science  English  Total    Average  Result
0    Ravi    80       90       85    255  85.000000    True
1    Sita    70       75       80    225  75.000000   False
2    Arun    95       88       92    275  91.666667    True
