In [1]:
import numpy as np

a = np.array(45)
print(a)

45


In [2]:
import numpy as np
temperature = np.array(35)
print(temperature)
print(temperature.ndim)

35
0


In [3]:
# Problem on Vector
import numpy as np
a = np.array([1, 2, 3, 4])
print(a + 1)

[2 3 4 5]


In [ ]:
#vectors addition
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

In [4]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.dot(A, B))

32


In [5]:
#matrix addition
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


In [6]:
# Matrix Addition
import numpy as np
a = np.array([[1,2,3],[4,5,6],[1,2,3]])
b = np.array([[1,2,3],[2,3,4],[1,2,3]])
print(a + b)

[[ 2  4  6]
 [ 6  8 10]
 [ 2  4  6]]


In [ ]:
#matrix multiplication
import numpy as np
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
print(A @ B)

[[19 22]
 [43 50]]


In [8]:
# Probability of getting Head
total_outcomes = 2
favourable_outcomes = 1
probability = favourable_outcomes / total_outcomes
print("Probability of Head:", probability)

Probability of Head: 0.5


In [9]:
# Probability of getting an even number
dice = [1, 2, 3, 4, 5, 6]
even = 0
for i in dice:
    if i % 2 == 0:
        even += 1
probability = even / len(dice)
print("Probability of getting an even number:", probability)

Probability of getting an even number: 0.5


In [10]:
# Probability of selecting a blue ball

red_balls = 10
blue_balls = 5
total_balls = red_balls + blue_balls
probability = blue_balls / total_balls

print("Probability of selecting a blue ball:", probability)

Probability of selecting a blue ball: 0.3333333333333333


In [25]:
a = 0.02
b = 0.95
c = 0.05

answer = (a * b) / c

print(answer)

0.37999999999999995


In [15]:
import numpy as np
data = np.array([12, 18, 24, 30, 36])
print(np.mean(data))

24.0


In [16]:
import numpy as np
data = np.array([12, 18, 24, 30, 36])
print(np.median(data))

24.0


In [17]:
import numpy as np
data = np.array([12, 18, 24, 30, 36])
print(np.var(data))

72.0


In [18]:
import numpy as np
data = np.array([12, 18, 24, 30, 36])
print(np.std(data))

8.48528137423857


In [19]:
import numpy as np
marks = np.array([78, 82, 91, 65, 84, 76, 89])
print("Mean:", np.mean(marks))
print("Variance:", np.var(marks))
print("Standard Deviation:", np.std(marks))

Mean: 80.71428571428571
Variance: 66.20408163265306
Standard Deviation: 8.13658906622751


In [20]:
from statistics import mode
marks = [78, 82, 91, 65, 84, 76, 89, 82]
print(mode(marks))

82


In [26]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


In [22]:
import numpy as np
hours = np.array([1, 2, 3, 4, 5])
marks = np.array([40, 50, 60, 70, 80])
corr = np.corrcoef(hours, marks)[0][1]
print("Correlation:", corr)
if corr > 0:
    print("Positive Correlation")
elif corr < 0:
    print("Negative Correlation")
else:
    print("No Correlation")

Correlation: 1.0
Positive Correlation


In [24]:
import numpy as np
data = np.random.normal(50, 10, 10)
print(data)

[45.07158646 51.29087408 51.13424784 31.05947915 67.76381749 67.4701398
 61.03607407 66.95979594 46.53242273 61.20066549]
